[build]
  # Ajusta según tu setup; aquí asumimos que tu build va a `dist/`
  publish = "dist"

[[redirects]]
  from = "/assets/*"
  to   = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/maintenance.html"
  status = 200
